name: my_tube
description: "MyTube"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Add dependencies here
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  logger: ^2.5.0
  like_button: ^2.0.5
  video_player: ^2.9.5
  cached_network_image: ^3.4.1
  tabler_icons: ^2.5.0+1
  hugeicons: ^0.0.11
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6



flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#000000" # or your background color
  image: "assets/icon/icon.png"
  android: true
  ios: true
  fullscreen: true

  color_dark: "#000000" # Transparent background for dark mode
  image_dark: "assets/icon/icon.png" # Use same image unless you have an inverted one

  android_12:
    image: "assets/icon/icon.png"
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

    image_dark: "assets/icon/icon.png"
    color_dark: "#000000"
    icon_background_color_dark: "#000000"

